Auto-promote elements defined by using the 'sub1.k1 = 5' mechanic.
This whole mechanic is only used because SBML doesn't have an equivalent.  Add to this the fact that Antimony follows rules instead of storing them means that this whole shebang is much more complicated than it could have been, but, you know, 17-year-old code.  So!  With a lot of Claude and a lot of tests, this should work in most cases.

Exception:  if you load an Antimony model into the library, ask it for the SBML-comp version, then ask it for the Antimony version.  Shouldn't happen very often, if at all.